version: 2
jobs:
  build:
    docker:
      - image: trion/ng-cli:1.5.0
    steps:
      - run: echo '
             github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
             bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
             ' >> ~/.ssh/known_hosts
      - checkout
      - run: npm install
      - run: ng build
      - persist_to_workspace:
          root: .
          paths:
            - dist
            - k8s
  deploy-k8s:
    docker:
      - image: kolov/aws-cli:1.1
    environment:
      - BUILD_TARGET_DIR: dist
      - APP_NAME: curri-fe
      - K8S_DEPLOYMENT: k8s/k8s-deployment.yml
      - K8S_SERVICE: k8s/k8s-service.yml
    steps:
      - attach_workspace:
          at: "."
      - type: setup-docker-engine
      - run: wget https://raw.githubusercontent.com/kolov/k8s-stuff/master/circleci/deploy-workflow.sh
      - run: chmod +x deploy-workflow.sh
      - run: cat ./deploy-workflow.sh
      - run: ./deploy-workflow.sh
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          context: org-global
      - deploy-k8s:
          requires:
            - build
          context: org-global
